// Package lockfile handles reading, writing, and resolving moca.lock files.
// The lockfile ensures reproducible app installs across environments by recording
// exact versions, sources, and checksums for all project apps.
//
// Read supports both YAML (current format) and JSON (backward compatibility).
// Write always outputs YAML per MOCA_CLI_SYSTEM_DESIGN.md §3.2.
package lockfile

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"time"

	"github.com/moca-framework/moca/pkg/apps"
	"gopkg.in/yaml.v3"
)

// Lockfile represents the parsed contents of moca.lock.
type Lockfile struct {
	GeneratedAt time.Time          `yaml:"generated_at" json:"generated_at"`
	Apps        map[string]AppLock `yaml:"apps"         json:"apps"`
	MocaVersion string             `yaml:"moca_version" json:"moca_version"`
}

// AppLock represents a single locked app entry.
type AppLock struct {
	Dependencies map[string]string `yaml:"dependencies,omitempty" json:"dependencies,omitempty"`
	Version      string            `yaml:"version"                json:"version"`
	Source       string            `yaml:"source"                 json:"source"`
	Ref          string            `yaml:"ref,omitempty"          json:"ref,omitempty"`
	Checksum     string            `yaml:"checksum,omitempty"     json:"checksum,omitempty"`
}

// Read loads a moca.lock file from the given path.
// It auto-detects JSON (legacy) vs YAML format for backward compatibility.
func Read(path string) (*Lockfile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read lockfile %s: %w", path, err)
	}

	var lf Lockfile
	if isJSON(data) {
		if err := json.Unmarshal(data, &lf); err != nil {
			return nil, fmt.Errorf("parse lockfile %s as JSON: %w", path, err)
		}
	} else {
		if err := yaml.Unmarshal(data, &lf); err != nil {
			return nil, fmt.Errorf("parse lockfile %s as YAML: %w", path, err)
		}
	}

	if lf.Apps == nil {
		lf.Apps = make(map[string]AppLock)
	}

	return &lf, nil
}

// Write serializes the lockfile to YAML and writes it to the given path.
// It sets GeneratedAt to the current UTC time if zero.
func Write(path string, lf *Lockfile) error {
	if lf.GeneratedAt.IsZero() {
		lf.GeneratedAt = time.Now().UTC()
	}

	data, err := yaml.Marshal(lf)
	if err != nil {
		return fmt.Errorf("marshal lockfile: %w", err)
	}

	header := []byte("# Auto-generated by 'moca app resolve'. Do not edit manually.\n")
	content := append(header, data...)

	return os.WriteFile(path, content, 0o644)
}

// ComputeChecksum computes the SHA256 checksum of a file.
// Returns a string in the format "sha256:<hex>".
func ComputeChecksum(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", fmt.Errorf("open %s for checksum: %w", path, err)
	}
	defer f.Close() //nolint:errcheck

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", fmt.Errorf("read %s for checksum: %w", path, err)
	}

	return "sha256:" + hex.EncodeToString(h.Sum(nil)), nil
}

// ResolveOptions controls lockfile resolution behavior.
type ResolveOptions struct {
	// Strict fails if any inter-app dependency constraint cannot be satisfied.
	Strict bool
	// Update allows updating locked versions within constraints (currently unused).
	Update bool
}

// Resolve scans all apps in appsDir, validates inter-app dependencies,
// computes checksums, and returns a fully populated Lockfile.
// It does not write to disk; call Write separately.
func Resolve(appsDir, mocaVersion string, opts ResolveOptions) (*Lockfile, error) {
	appInfos, err := apps.ScanApps(appsDir)
	if err != nil {
		return nil, fmt.Errorf("scan apps: %w", err)
	}

	if opts.Strict {
		if err := apps.ValidateDependencies(appInfos); err != nil {
			return nil, fmt.Errorf("dependency validation: %w", err)
		}
	}

	lf := &Lockfile{
		GeneratedAt: time.Now().UTC(),
		MocaVersion: mocaVersion,
		Apps:        make(map[string]AppLock, len(appInfos)),
	}

	for _, ai := range appInfos {
		lock := AppLock{
			Version: ai.Manifest.Version,
		}

		// Determine source.
		lock.Source = resolveSource(ai)

		// Compute checksum of manifest.yaml.
		manifestPath := filepath.Join(ai.Path, "manifest.yaml")
		checksum, err := ComputeChecksum(manifestPath)
		if err != nil {
			return nil, fmt.Errorf("checksum %s: %w", ai.Name, err)
		}
		lock.Checksum = checksum

		// Record dependencies.
		if len(ai.Manifest.Dependencies) > 0 {
			lock.Dependencies = make(map[string]string, len(ai.Manifest.Dependencies))
			for _, dep := range ai.Manifest.Dependencies {
				constraint := dep.MinVersion
				if constraint == "" {
					constraint = "*"
				}
				lock.Dependencies[dep.App] = constraint
			}
		}

		lf.Apps[ai.Name] = lock
	}

	return lf, nil
}

// resolveSource determines the source string for a locked app entry.
// For now, checks if the app dir contains a .git directory (external source)
// or defaults to "builtin".
func resolveSource(ai apps.AppInfo) string {
	gitDir := filepath.Join(ai.Path, ".git")
	if info, err := os.Stat(gitDir); err == nil && info.IsDir() {
		// Try to read the git remote URL.
		if remote := readGitRemote(ai.Path); remote != "" {
			return remote
		}
		return "git"
	}
	return "builtin"
}

// readGitRemote reads the origin remote URL from a git repository.
func readGitRemote(dir string) string {
	configPath := filepath.Join(dir, ".git", "config")
	data, err := os.ReadFile(configPath)
	if err != nil {
		return ""
	}
	// Simple heuristic: find "url = " after "[remote \"origin\"]".
	lines := bytes.Split(data, []byte("\n"))
	inOrigin := false
	for _, line := range lines {
		trimmed := bytes.TrimSpace(line)
		if bytes.Equal(trimmed, []byte(`[remote "origin"]`)) {
			inOrigin = true
			continue
		}
		if inOrigin {
			if bytes.HasPrefix(trimmed, []byte("[")) {
				break
			}
			if bytes.HasPrefix(trimmed, []byte("url = ")) {
				return string(bytes.TrimSpace(trimmed[6:]))
			}
		}
	}
	return ""
}

// isJSON detects if content is JSON by checking if the first non-whitespace byte is '{'.
func isJSON(data []byte) bool {
	for _, b := range data {
		switch b {
		case ' ', '\t', '\n', '\r':
			continue
		case '{':
			return true
		default:
			return false
		}
	}
	return false
}
