package scaffold

// deskTemplateData holds values available to desk scaffold templates.
type deskTemplateData struct {
	ProjectName     string // e.g. "my-erp"
	MocaDeskVersion string // e.g. "0.1.0"
	MocaDeskSpec    string // npm spec: "^0.1.0" or "file:../../desk"
}

const deskPackageJSONTmpl = `{
  "name": "{{.ProjectName}}-desk",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "@osama1998h/desk": "{{.MocaDeskSpec}}",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@tailwindcss/vite": "^4.0.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "@vitejs/plugin-react": "^6.0.0",
    "tailwindcss": "^4.0.0",
    "typescript": "~6.0.0",
    "vite": "^8.0.0"
  }
}
`

const deskIndexHTMLTmpl = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Moca Desk</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`

const deskViteConfigTmpl = `import { defineConfig } from "vite";
import { mocaDeskPlugin } from "@osama1998h/desk/vite";

export default defineConfig({
  plugins: [mocaDeskPlugin()],
  // The plugin handles: React, TailwindCSS, base path (/desk/),
  // API proxy, WebSocket proxy, app extension discovery.
  // Override any setting here if needed.
});
`

const deskTsconfigTmpl = `{
  "files": [],
  "references": [
    { "path": "./tsconfig.app.json" },
    { "path": "./tsconfig.node.json" }
  ]
}
`

const deskTsconfigAppTmpl = `{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true,
    "noUncheckedSideEffectImports": true,
    "composite": true
  },
  "include": ["src", ".moca-extensions.ts"]
}
`

const deskTsconfigNodeTmpl = `{
  "compilerOptions": {
    "target": "ES2022",
    "lib": ["ES2023"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "composite": true
  },
  "include": ["vite.config.ts"]
}
`

const deskMainTsxTmpl = `import { createDeskApp } from "@osama1998h/desk";
import "../.moca-extensions";
import "./overrides";

const app = createDeskApp({
  siteName: import.meta.env.VITE_MOCA_SITE,
  // Project-level configuration
  // theme: { ... },
  // logo: "/path/to/logo.svg",
  // defaultLocale: "en",
});

app.mount("#root");
`

const deskOverridesIndexTmpl = `// Project-level overrides for Moca Desk.
// Import custom field types, pages, sidebar items, or theme overrides here.
// These run after app extensions and can override any framework default.
//
// Example:
//   import { registerFieldType } from "@osama1998h/desk";
//   import MyCustomField from "./MyCustomField";
//   registerFieldType("MyCustom", MyCustomField);

export {};
`

const deskOverridesThemeTmpl = `// Theme and branding overrides for this project.
// Customize colors, logo, and other visual settings here.
//
// Example:
//   import { createDeskApp } from "@osama1998h/desk";
//   // Pass theme overrides to createDeskApp() in main.tsx:
//   // createDeskApp({ theme: { primaryColor: "#1a73e8" } })

export {};
`

const deskEnvTmpl = `VITE_MOCA_SITE=
`

const deskGitignoreTmpl = `node_modules/
dist/
.vite/
*.tsbuildinfo
.moca-extensions.ts
.env
.env.local
`

const deskNpmrcTmpl = `@osama1998h:registry=https://npm.pkg.github.com
`

const deskExtensionsStubTmpl = `// Auto-generated by 'moca build desk'. Do not edit.
// No app desk extensions discovered.
`
