package generate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/osama1998H/moca/internal/config"
)

// testConfig returns a ProjectConfig suitable for testing all generators.
func testConfig(kafkaEnabled bool) *config.ProjectConfig {
	enabled := kafkaEnabled
	return &config.ProjectConfig{
		Project: config.ProjectInfo{
			Name:    "test-erp",
			Version: "1.0.0",
		},
		Production: config.ProductionConfig{
			Port:     8000,
			Workers:  "4",
			LogLevel: "info",
			TLS: config.TLSConfig{
				Provider: "acme",
				Email:    "admin@example.com",
			},
			Proxy: config.ProxyConfig{
				Engine: "caddy",
			},
			ProcessManager: "systemd",
		},
		Infrastructure: config.InfrastructureConfig{
			Database: config.DatabaseConfig{
				Host:     "localhost",
				Port:     5432,
				User:     "moca",
				Password: "secret",
				SystemDB: "moca_db",
				PoolSize: 10,
			},
			Redis: config.RedisConfig{
				Host:      "localhost",
				Port:      6379,
				Password:  "redis_secret",
				DbCache:   0,
				DbQueue:   1,
				DbSession: 2,
				DbPubSub:  3,
			},
			Kafka: config.KafkaConfig{
				Enabled: &enabled,
				Brokers: []string{"kafka:9092"},
			},
			Search: config.SearchConfig{
				Engine: "meilisearch",
				Host:   "localhost",
				Port:   7700,
				APIKey: "meili_key",
			},
			Storage: config.StorageConfig{
				Driver:    "s3",
				Endpoint:  "http://minio:9000",
				Bucket:    "moca-files",
				AccessKey: "minioadmin",
				SecretKey: "minioadmin",
			},
		},
		Scheduler: config.SchedulerConfig{
			Enabled:      true,
			TickInterval: "5m",
		},
	}
}

// ---------------------------------------------------------------------------
// Foundation
// ---------------------------------------------------------------------------

func TestKafkaEnabled(t *testing.T) {
	t.Run("nil", func(t *testing.T) {
		if KafkaEnabled(config.KafkaConfig{Enabled: nil}) {
			t.Error("expected false for nil Enabled")
		}
	})
	t.Run("true", func(t *testing.T) {
		enabled := true
		if !KafkaEnabled(config.KafkaConfig{Enabled: &enabled}) {
			t.Error("expected true for *true Enabled")
		}
	})
	t.Run("false", func(t *testing.T) {
		enabled := false
		if KafkaEnabled(config.KafkaConfig{Enabled: &enabled}) {
			t.Error("expected false for *false Enabled")
		}
	})
}

func TestRenderToFile(t *testing.T) {
	dir := t.TempDir()
	// Nested directory that doesn't exist yet.
	path := filepath.Join(dir, "sub", "deep", "out.txt")

	err := renderToFile(path, "Hello {{.Name}}", map[string]string{"Name": "World"})
	if err != nil {
		t.Fatalf("renderToFile: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if string(data) != "Hello World" {
		t.Errorf("got %q, want %q", data, "Hello World")
	}
}

func TestFileHeader(t *testing.T) {
	h := fileHeader()
	if !strings.Contains(h, "Generated by Moca") {
		t.Errorf("header missing expected text: %q", h)
	}
}

// ---------------------------------------------------------------------------
// Caddy
// ---------------------------------------------------------------------------

func TestGenerateCaddy(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(false)
	out := filepath.Join(dir, "Caddyfile")

	paths, err := GenerateCaddy(cfg, "/opt/moca", CaddyOptions{
		OutputPath: out,
		Domain:     "example.com",
	})
	if err != nil {
		t.Fatalf("GenerateCaddy: %v", err)
	}
	if len(paths) != 1 || paths[0] != out {
		t.Fatalf("unexpected paths: %v", paths)
	}

	data, _ := os.ReadFile(out)
	content := string(data)

	for _, want := range []string{"reverse_proxy", "localhost:8000", "example.com", "Generated by Moca"} {
		if !strings.Contains(content, want) {
			t.Errorf("Caddyfile missing %q", want)
		}
	}
}

func TestGenerateCaddy_Multitenant(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(false)
	out := filepath.Join(dir, "Caddyfile")

	_, err := GenerateCaddy(cfg, "/opt/moca", CaddyOptions{
		OutputPath:  out,
		Multitenant: true,
		Domain:      "example.com",
	})
	if err != nil {
		t.Fatalf("GenerateCaddy multitenant: %v", err)
	}

	data, _ := os.ReadFile(out)
	content := string(data)

	if !strings.Contains(content, "*.example.com") {
		t.Error("Caddyfile missing wildcard domain for multitenant")
	}
	if !strings.Contains(content, "X-Moca-Site") {
		t.Error("Caddyfile missing X-Moca-Site header for multitenant")
	}
}

// ---------------------------------------------------------------------------
// NGINX
// ---------------------------------------------------------------------------

func TestGenerateNginx(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(false)
	out := filepath.Join(dir, "moca.conf")

	paths, err := GenerateNginx(cfg, "/opt/moca", NginxOptions{
		OutputPath: out,
		Domain:     "example.com",
	})
	if err != nil {
		t.Fatalf("GenerateNginx: %v", err)
	}
	if len(paths) != 1 {
		t.Fatalf("unexpected paths: %v", paths)
	}

	data, _ := os.ReadFile(out)
	content := string(data)

	for _, want := range []string{"upstream moca_server", "proxy_pass", "example.com", "127.0.0.1:8000"} {
		if !strings.Contains(content, want) {
			t.Errorf("NGINX config missing %q", want)
		}
	}
}

// ---------------------------------------------------------------------------
// Systemd
// ---------------------------------------------------------------------------

func TestGenerateSystemd_WithKafka(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(true)

	paths, err := GenerateSystemd(cfg, "/opt/moca", SystemdOptions{
		OutputDir: dir,
		User:      "moca",
	})
	if err != nil {
		t.Fatalf("GenerateSystemd (kafka): %v", err)
	}

	// Expect 6 files: server@, worker@, scheduler, outbox, search-sync, target.
	if len(paths) != 6 {
		t.Fatalf("expected 6 files, got %d: %v", len(paths), paths)
	}

	// Verify key files exist and have correct content.
	serverData, _ := os.ReadFile(filepath.Join(dir, "moca-server@.service"))
	serverContent := string(serverData)
	for _, want := range []string{"[Unit]", "[Service]", "ExecStart=", "moca-server"} {
		if !strings.Contains(serverContent, want) {
			t.Errorf("server unit missing %q", want)
		}
	}

	targetData, _ := os.ReadFile(filepath.Join(dir, "moca.target"))
	targetContent := string(targetData)
	if !strings.Contains(targetContent, "moca-outbox.service") {
		t.Error("target missing outbox (kafka is enabled)")
	}
}

func TestGenerateSystemd_WithoutKafka(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(false)

	paths, err := GenerateSystemd(cfg, "/opt/moca", SystemdOptions{
		OutputDir: dir,
	})
	if err != nil {
		t.Fatalf("GenerateSystemd (no kafka): %v", err)
	}

	// Expect 4 files: server@, worker@, scheduler, target.
	if len(paths) != 4 {
		t.Fatalf("expected 4 files, got %d: %v", len(paths), paths)
	}

	// Outbox and search-sync should NOT exist.
	if _, err := os.Stat(filepath.Join(dir, "moca-outbox.service")); err == nil {
		t.Error("outbox unit generated when Kafka is disabled")
	}
	if _, err := os.Stat(filepath.Join(dir, "moca-search-sync.service")); err == nil {
		t.Error("search-sync unit generated when Kafka is disabled")
	}

	targetData, _ := os.ReadFile(filepath.Join(dir, "moca.target"))
	targetContent := string(targetData)
	if strings.Contains(targetContent, "moca-outbox.service") {
		t.Error("target references outbox when Kafka is disabled")
	}
}

func TestGenerateSystemd_TargetWants(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(true)

	_, err := GenerateSystemd(cfg, "/opt/moca", SystemdOptions{OutputDir: dir})
	if err != nil {
		t.Fatalf("GenerateSystemd: %v", err)
	}

	targetData, _ := os.ReadFile(filepath.Join(dir, "moca.target"))
	content := string(targetData)

	for _, unit := range []string{
		"moca-server@.service",
		"moca-worker@.service",
		"moca-scheduler.service",
		"moca-outbox.service",
		"moca-search-sync.service",
	} {
		if !strings.Contains(content, unit) {
			t.Errorf("target missing Wants=%s", unit)
		}
	}
}

// ---------------------------------------------------------------------------
// Docker
// ---------------------------------------------------------------------------

func TestGenerateDocker(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(false)

	paths, err := GenerateDocker(cfg, "/opt/moca", DockerOptions{
		OutputDir: dir,
		Profile:   "production",
	})
	if err != nil {
		t.Fatalf("GenerateDocker: %v", err)
	}

	// Production profile: compose, Dockerfile, .dockerignore, compose.prod.
	if len(paths) != 4 {
		t.Fatalf("expected 4 files, got %d: %v", len(paths), paths)
	}

	composeData, _ := os.ReadFile(filepath.Join(dir, "docker-compose.yml"))
	content := string(composeData)

	for _, want := range []string{"services:", "postgres:", "redis:", "moca-server:", "moca-worker:"} {
		if !strings.Contains(content, want) {
			t.Errorf("docker-compose.yml missing %q", want)
		}
	}

	// Verify Dockerfile exists and has multi-stage build.
	dfData, _ := os.ReadFile(filepath.Join(dir, "Dockerfile"))
	dfContent := string(dfData)
	if !strings.Contains(dfContent, "FROM golang:") {
		t.Error("Dockerfile missing builder stage")
	}
	if !strings.Contains(dfContent, "FROM debian:") {
		t.Error("Dockerfile missing runtime stage")
	}
}

func TestGenerateDocker_KafkaIncluded(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(true)

	_, err := GenerateDocker(cfg, "/opt/moca", DockerOptions{OutputDir: dir})
	if err != nil {
		t.Fatalf("GenerateDocker: %v", err)
	}

	data, _ := os.ReadFile(filepath.Join(dir, "docker-compose.yml"))
	content := string(data)

	if !strings.Contains(content, "kafka:") {
		t.Error("docker-compose.yml missing kafka service when Kafka enabled")
	}
	if !strings.Contains(content, "moca-outbox:") {
		t.Error("docker-compose.yml missing moca-outbox when Kafka enabled")
	}
}

// ---------------------------------------------------------------------------
// Kubernetes
// ---------------------------------------------------------------------------

func TestGenerateK8s(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(true)

	paths, err := GenerateK8s(cfg, "/opt/moca", K8sOptions{
		OutputDir: dir,
		Namespace: "production",
		Replicas:  3,
	})
	if err != nil {
		t.Fatalf("GenerateK8s: %v", err)
	}

	if len(paths) != 7 {
		t.Fatalf("expected 7 manifests, got %d: %v", len(paths), paths)
	}

	// Verify deployment has correct apiVersion and kind.
	depData, _ := os.ReadFile(filepath.Join(dir, "deployment.yaml"))
	depContent := string(depData)
	if !strings.Contains(depContent, "apiVersion: apps/v1") {
		t.Error("deployment.yaml missing apiVersion")
	}
	if !strings.Contains(depContent, "kind: Deployment") {
		t.Error("deployment.yaml missing kind")
	}
	if !strings.Contains(depContent, "replicas: 3") {
		t.Error("deployment.yaml missing correct replica count")
	}

	// Verify service.
	svcData, _ := os.ReadFile(filepath.Join(dir, "service.yaml"))
	if !strings.Contains(string(svcData), "kind: Service") {
		t.Error("service.yaml missing kind")
	}

	// Verify HPA has TODO comment.
	hpaData, _ := os.ReadFile(filepath.Join(dir, "hpa.yaml"))
	if !strings.Contains(string(hpaData), "TODO") {
		t.Error("hpa.yaml missing TODO comment for Prometheus")
	}

	// Verify PDB.
	pdbData, _ := os.ReadFile(filepath.Join(dir, "pdb.yaml"))
	if !strings.Contains(string(pdbData), "kind: PodDisruptionBudget") {
		t.Error("pdb.yaml missing kind")
	}
}

func TestGenerateK8s_KafkaDisabled(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(false)

	_, err := GenerateK8s(cfg, "/opt/moca", K8sOptions{OutputDir: dir})
	if err != nil {
		t.Fatalf("GenerateK8s: %v", err)
	}

	depData, _ := os.ReadFile(filepath.Join(dir, "deployment.yaml"))
	content := string(depData)

	if strings.Contains(content, "moca-outbox") {
		t.Error("deployment.yaml contains moca-outbox when Kafka is disabled")
	}
	if strings.Contains(content, "moca-search-sync") {
		t.Error("deployment.yaml contains moca-search-sync when Kafka is disabled")
	}
}

// ---------------------------------------------------------------------------
// Supervisor
// ---------------------------------------------------------------------------

func TestGenerateSupervisor(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(true)
	out := filepath.Join(dir, "supervisord.conf")

	paths, err := GenerateSupervisor(cfg, "/opt/moca", SupervisorOptions{
		OutputPath: out,
		User:       "moca",
	})
	if err != nil {
		t.Fatalf("GenerateSupervisor: %v", err)
	}
	if len(paths) != 1 {
		t.Fatalf("unexpected paths: %v", paths)
	}

	data, _ := os.ReadFile(out)
	content := string(data)

	for _, want := range []string{
		"[supervisord]",
		"[program:moca-server]",
		"[program:moca-worker]",
		"[program:moca-scheduler]",
		"[program:moca-outbox]",
		"[group:moca]",
	} {
		if !strings.Contains(content, want) {
			t.Errorf("supervisord.conf missing %q", want)
		}
	}
}

func TestGenerateSupervisor_NoKafka(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(false)
	out := filepath.Join(dir, "supervisord.conf")

	_, err := GenerateSupervisor(cfg, "/opt/moca", SupervisorOptions{OutputPath: out})
	if err != nil {
		t.Fatalf("GenerateSupervisor: %v", err)
	}

	data, _ := os.ReadFile(out)
	content := string(data)

	if strings.Contains(content, "[program:moca-outbox]") {
		t.Error("supervisord.conf has outbox program when Kafka disabled")
	}
}

// ---------------------------------------------------------------------------
// Env
// ---------------------------------------------------------------------------

func TestGenerateEnv_Dotenv(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(false)
	out := filepath.Join(dir, ".env")

	paths, err := GenerateEnv(cfg, "/opt/moca", EnvOptions{
		OutputPath: out,
		Format:     "dotenv",
	})
	if err != nil {
		t.Fatalf("GenerateEnv: %v", err)
	}
	if len(paths) != 1 {
		t.Fatalf("unexpected paths: %v", paths)
	}

	data, _ := os.ReadFile(out)
	content := string(data)

	// Verify KEY=VALUE format.
	for _, want := range []string{
		"MOCA_PROJECT_NAME=test-erp",
		"MOCA_DB_HOST=localhost",
		"MOCA_DB_PORT=5432",
		"MOCA_REDIS_HOST=localhost",
		"MOCA_PORT=8000",
	} {
		if !strings.Contains(content, want) {
			t.Errorf(".env missing %q", want)
		}
	}

	// Kafka disabled — should not have Kafka section.
	if strings.Contains(content, "MOCA_KAFKA_ENABLED=true") {
		t.Error(".env has Kafka entries when disabled")
	}
}

func TestGenerateEnv_Systemd(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(true)
	out := filepath.Join(dir, "env.systemd")

	_, err := GenerateEnv(cfg, "/opt/moca", EnvOptions{
		OutputPath: out,
		Format:     "systemd",
	})
	if err != nil {
		t.Fatalf("GenerateEnv systemd: %v", err)
	}

	data, _ := os.ReadFile(out)
	content := string(data)

	// Systemd format uses Environment="KEY=VALUE".
	if !strings.Contains(content, `Environment="MOCA_DB_HOST=localhost"`) {
		t.Error("systemd env missing Environment= format")
	}
	if !strings.Contains(content, `Environment="MOCA_KAFKA_ENABLED=true"`) {
		t.Error("systemd env missing Kafka when enabled")
	}
}

func TestGenerateEnv_Docker(t *testing.T) {
	dir := t.TempDir()
	cfg := testConfig(false)
	out := filepath.Join(dir, ".env.docker")

	_, err := GenerateEnv(cfg, "/opt/moca", EnvOptions{
		OutputPath: out,
		Format:     "docker",
	})
	if err != nil {
		t.Fatalf("GenerateEnv docker: %v", err)
	}

	data, _ := os.ReadFile(out)
	content := string(data)

	if !strings.Contains(content, "MOCA_PROJECT_NAME=test-erp") {
		t.Error("docker env missing project name")
	}
	// Docker format should NOT have Environment= prefix.
	if strings.Contains(content, `Environment="`) {
		t.Error("docker format incorrectly uses systemd Environment= prefix")
	}
}

// ---------------------------------------------------------------------------
// Default helpers
// ---------------------------------------------------------------------------

func TestDefaultPort(t *testing.T) {
	cfg := &config.ProjectConfig{}
	if got := defaultPort(cfg); got != 8000 {
		t.Errorf("defaultPort empty = %d, want 8000", got)
	}

	cfg.Production.Port = 9090
	if got := defaultPort(cfg); got != 9090 {
		t.Errorf("defaultPort 9090 = %d, want 9090", got)
	}
}

func TestDefaultWorkers(t *testing.T) {
	cfg := &config.ProjectConfig{}
	if got := defaultWorkers(cfg); got != "auto" {
		t.Errorf("defaultWorkers empty = %q, want %q", got, "auto")
	}

	cfg.Production.Workers = "4"
	if got := defaultWorkers(cfg); got != "4" {
		t.Errorf("defaultWorkers 4 = %q, want %q", got, "4")
	}
}

func TestDefaultLogLevel(t *testing.T) {
	cfg := &config.ProjectConfig{}
	if got := defaultLogLevel(cfg); got != "info" {
		t.Errorf("defaultLogLevel empty = %q, want %q", got, "info")
	}

	cfg.Production.LogLevel = "debug"
	if got := defaultLogLevel(cfg); got != "debug" {
		t.Errorf("defaultLogLevel debug = %q, want %q", got, "debug")
	}
}
