// Package generate renders infrastructure configuration files from a Moca
// ProjectConfig. It supports Caddy, NGINX, systemd, Docker Compose,
// Kubernetes, supervisord, and environment file generation.
package generate

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"text/template"

	"github.com/osama1998H/moca/internal/config"
)

// KafkaEnabled returns true if Kafka is explicitly enabled in the config.
func KafkaEnabled(cfg config.KafkaConfig) bool {
	return cfg.Enabled != nil && *cfg.Enabled
}

// fileHeader returns the standard header comment for generated files.
func fileHeader() string {
	return "# Generated by Moca — do not edit manually."
}

// renderToFile parses tmplText as a text/template, executes it against data,
// and writes the result to path. Parent directories are created as needed.
func renderToFile(path, tmplText string, data any) error {
	if err := ensureDir(path); err != nil {
		return fmt.Errorf("create directory for %s: %w", path, err)
	}

	t, err := template.New(filepath.Base(path)).Parse(tmplText)
	if err != nil {
		return fmt.Errorf("parse template %s: %w", filepath.Base(path), err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute template %s: %w", filepath.Base(path), err)
	}

	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// ensureDir creates the parent directory of path if it does not exist.
func ensureDir(path string) error {
	return os.MkdirAll(filepath.Dir(path), 0o755)
}

// defaultPort returns the production port from config, falling back to 8000.
func defaultPort(cfg *config.ProjectConfig) int {
	if cfg.Production.Port > 0 {
		return cfg.Production.Port
	}
	return 8000
}

// defaultWorkers returns the production workers setting, falling back to "auto".
func defaultWorkers(cfg *config.ProjectConfig) string {
	if cfg.Production.Workers != "" {
		return cfg.Production.Workers
	}
	return "auto"
}

// defaultLogLevel returns the production log level, falling back to "info".
func defaultLogLevel(cfg *config.ProjectConfig) string {
	if cfg.Production.LogLevel != "" {
		return cfg.Production.LogLevel
	}
	return "info"
}
